# 1.SpringCloud配置
spring:
  application:
    name: ccait.ccweb #服务名
  datasource:
    druid:
      test-on-borrow: true
      test-while-idle: true
  zipkin: #分布式链路配置
    base-url: http://localhost:9411
  thymeleaf:
    cache: false
  devtools: #dev tools
    livereload:
      enabled: true
  session:
    store-type: none #none, redis, mongo
    cookie:
      max-age: 43200000
    persistent: true

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  mvc:
    async:
      request-timeout: 43200000
    static-path-pattern: /** #静态文件请求匹配方式
  resources: #修改默认的静态寻址资源目录
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  redis:
    host: 127.0.0.1
    port: 6667
    database: 0
    timeout: 6000000


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #注册中心



feign:
  hystrix:
    enabled: true


# 2.服务器配置
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080 #端口号

# 3.logging配置
logging:
  config: classpath:logback.xml
  kafka:
    enabled: false
    #多个broker用英文逗号分隔
    broker: 127.0.0.1:9092
    #创建Kafka的topic时使用
    env: test
  level:
    com:
      netflix:
        discovery:
          DiscoveryClient: OFF
          InstanceInfoReplicato: OFF
      alibaba:
        druid:
          pool:
            DruidPooledPreparedStatement: OFF
      sun:
        jersey:
          client: OFF
    netflix:
      discovery:
        shared:
          transport:
            jersey:
              AbstractJerseyEurekaHttpClient: OFF

# 4.log4j配置
log4j:
  config:
    path: log4j2.xml #日志配置路径，可选
  logger:
    org:
      springframework:
        cloud: OFF

# 5.websocket配置
websocket:
  server: 127.0.0.1
  enable: true
  protocol: ws
  port: 8080


# 6.微信授权配置
weixin:
  mp:
    endpoint:
      # 微信回调地址，默认为 /weixin/callback，如需自定义，请修改以下配置项
      callback-url: /wechat/callback
    security:
      # 微信后台配置的 token
      token: 1234567890
      # 微信后台配置的消息加解密 aeskey
      encodingAesKey: abcdefghijklmnopqrstuvwxyz0123456789ABCDEFG
      # #############################################################
      # 微信 access token 过期刷新阈值，计算方法：
      # 当前时间 - (获得token时间 + token 有效期 + 阈值) < 0 则刷新 token
      # 默认为 token 失效前 5 分钟刷新
      # #############################################################
      refresh-token-threshold: 300
    auth:
      # APPID
      appid: appid
      # APP secret
      secret: secret


# 7.entityqueryable配置
entity:
  datasource:
    activated: ccweb #可通过url的{datasource}参数访问到该数据库，没有在此设置的environment不能通过url访问到
    #configFile: db-config.xml #数据库配置路径
    environments:
      ccweb:
        default: true
        driver: org.sqlite.JDBC
        url: jdbc:sqlite:ccait.db


# 8.ccweb配置
ccweb:
  lang: cn
  ignoreTotalCount: true #忽略查询总数
  package: ccait.ccweb.entites #实体类生成包路径
  suffix: Entity #实体类生成类名后辍
  page: #分页配置选项
    maxSize: 50 #分页最大记录数默认值
  defaultDateByNow: false
  app-config:
    table: app-config #表名
  auth:
    user:
      jwt:
        millis: 86000000
        enable: true
      aes:
        enable: false
      wechat:
        appid: openid4sa411f32sd1f1sa
        secret: tokenfd53sa411f32sd1f1sa
        enable: true

  security: #安全配置选项
    encrypt:
      MD5: #MD5加密配置
        fields: user.password,userinfo.password #需要使用MD5加密的字段，逗号分隔
        publicKey: ccait@2019 #MD5加密公钥
      AES: #AES加密配置
        publicKey: ccait@2019 #AES加密公钥
    admin: #超级管理员账号密码(必填)
      username: admin
      password: admin

  uniquekey:
    userinfo: username
    company: name
    steps: name
    attachmentType: name
    auditScope: name
    auditStatus: name
    workStatus: name

  formatter: #查询结果输出格式，createOn、modifyOn，也可以精确格式化:[表名].[字段名]
    createOn: yyyy-MM-dd HH:mm
    modifyOn: yyyy-MM-dd HH:mm
    start_time: yyyy-MM-dd HH:mm
    end_time: yyyy-MM-dd HH:mm
    startTime: yyyy-MM-dd HH:mm
    endTime: yyyy-MM-dd HH:mm
    evaluateTime: yyyy-MM-dd HH:mm
    appraise_time: yyyy-MM-dd HH:mm

  table:
    sync:
      userinfo:
        table: user
        fields:
          email: username
          password: password
          type: type
          key: key
          createBy: createBy
          createOn: createOn
      company:
        table: group
        fields:
          name: groupName
          type: type
      workflow:
        table: workflow
        fields:
          reviewer: createBy

    attach:
      items: steps
    template:
      workflow:
        itemsId: items
    attributeTableSuffix: Attrs
    reservedField: #系统保留字段(必填)
      userPath: userPath #创建者所属路径，体现父子关系，用于like查询
      createOn: createOn #数据创建时间
      createBy: createBy #数据创建者
      owner: owner #数据所有者
      modifyOn: modifyOn #数据修改时间
      modifyBy: modifyBy #数据修改人
      groupId: groupId  #群组ID
      roleId: roleId #角色ID
      aclId: aclId #访问控制ID
      privilegeId: privilegeId #权限ID
      userGroupRoleId: userGroupRoleId #用户组角色关联ID
      userId: userId #用户ID(整型，会被计算到userPath中)
      id: id #系统默认id字段名

    #系统保留表(必填)
    user: user #用户表
    group: group #分组表
    role: role #角色表
    acl: acl #访问控制表
    privilege: privilege #操作权限表
    userGroupRole: userGroupRole #用户/组/角色关联关系

    display: #需要隐藏的字段，设为hidden的字段不会在查询结果中显示
      user:
        password: hidden
      userinfo:
        password: hidden

  ui:
    type: element-plus
    default:
      controls:
        Id:
          componentName: el-select
        company.parent:
          componentName: el-select

        String:
          componentName: el-input
        Date:
          componentName: el-date-picker
        Boolean:
          componentName: el-checkbox
        Long:
          componentName: el-input-number
        Integer:
          componentName: el-input-number
        BigDecimal:
          componentName: el-input-number

  upload: #上传设置
    ccweb: #库名
      document: #表名
        attachment: #字段名
          maxSize: 16 #上传文件最大尺寸，单位: MB
          mimeType: gif, jpg, png, jpeg, xls, xlsx, doc, docx, ppt, pptx, pdf #允许上传的文件格式
          path: /upload/attachment


  download: #下载设置
    thumb:  #预览的缩略图
      fixedWidth: 200 #固定宽度
      scalRatio: 50 #缩放比率(百分比)
      watermark: ccweb #水印

  enableFlux: false   #是否开启web异步响应流

  #  ip:
  #    whiteList:  #IP白名单
  #    blackList:  #IP黑名单


  validation: #数据提交字段校验器，以下email、mobile为字段名，也可以精确校验:[表名].[字段名]
    userinfo.email:
      match: ^([a-zA-Z0-9_\-\.\u4e00-\u9fa5])+@([a-zA-Z0-9_\-\.\u4e00-\u9fa5])+(\.[a-zA-Z0-9_\-\u4e00-\u9fa5]+)+$
      message: 请输入正确的电子邮箱格式
    userinfo.password:
      match: ^[0-9a-zA-Z~\(\)!@#$%^&*]{6,12}$
      message: 请输入6至12位密码
    items.name:
      match: ^[\d\w\u4e00-\u9fa5]+$
      message: 请输入合法名称
    steps.name:
      match: ^[\d\w\u4e00-\u9fa5]+$
      message: 请输入合法名称
    attachmentType.name:
      match: ^[\d\w\u4e00-\u9fa5]+$
      message: 请输入合法名称
    auditScope.name:
      match: ^[\d\w\u4e00-\u9fa5]+$
      message: 请输入合法名称
    workStatus.name:
      match: ^[\d\w\u4e00-\u9fa5]+$
      message: 请输入合法名称
    workerflow.reviewer:
      match: ^[\d]+$
      message: 请选择委派人

  defaultValue: #指定表字段为null时赋于默认值，UUID_RANDOM=UUID.randomUUID()，DATE_NOW=new Date()
    userGroupRoleId: UUID_RANDOM
    userinfo.key: UUID_RANDOM

