#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Jul 18 00:44:28 CST 2024
maven-metadata-ccweb.xml.lastUpdated=1721234668997
maven-metadata-ali.xml.lastUpdated=1721234668975
maven-metadata-entity-orm.xml.lastUpdated=1721234668996
maven-metadata-ccweb.xml.error=
maven-metadata-entity-orm.xml.error=
maven-metadata-ali.xml.error=
