#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Jul 05 23:52:19 CST 2024
maven-metadata-ali.xml.error=
maven-metadata-ccweb.xml.lastUpdated=1720194739574
maven-metadata-entity-orm.xml.lastUpdated=1720194739565
maven-metadata-ccweb.xml.error=
maven-metadata-ali.xml.lastUpdated=1720194739558
maven-metadata-entity-orm.xml.error=
