#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sun Jul 21 16:56:23 CST 2024
maven-metadata-pentaho-releases.xml.error=Could not transfer metadata ccait.cn\:ccweb-core\:2.0.0-SNAPSHOT/maven-metadata.xml from/to pentaho-releases (http\://nexus.pentaho.org/content/groups/omni)\: Transfer failed for http\://nexus.pentaho.org/content/groups/omni/ccait/cn/ccweb-core/2.0.0-SNAPSHOT/maven-metadata.xml 503 Service Temporarily Unavailable
maven-metadata-ali.xml.error=
maven-metadata-ccweb.xml.lastUpdated=1721552183573
maven-metadata-entity-orm.xml.lastUpdated=1721552183770
maven-metadata-ccweb.xml.error=
maven-metadata-aspose-maven-repository.xml.error=
maven-metadata-pentaho-releases.xml/@default-pentaho-releases-http\://nexus.pentaho.org/content/groups/omni/.lastUpdated=1721493209632
maven-metadata-aspose-maven-repository.xml.lastUpdated=1721493209283
maven-metadata-entity-orm.xml.error=
maven-metadata-ali.xml.lastUpdated=1721552183699
