#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Jul 05 21:34:49 CST 2024
maven-metadata-ccweb.xml.lastUpdated=1720186489014
maven-metadata-entity-orm.xml.lastUpdated=1720186489009
maven-metadata-ali.xml.lastUpdated=1720186489065
maven-metadata-ccweb.xml.error=
maven-metadata-entity-orm.xml.error=
maven-metadata-ali.xml.error=
